# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: fief
'on':
  schedule:
    - cron: "13 4 * * *"
concurrency:
  group: fief
  cancel-in-progress: true
jobs:
  fief:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.6
          bundler-cache: true
      - run: gem install fief
      - run: |
          fief --token ${{ secrets.TOKEN }} --delay 1000 \
            --include objectionary/* \
            --include polystat/* \
            --exclude objectionary/.github \
            --exclude polystat/.github \
            --to html
      - run: mkdir gh-pages
      - run: cp html/index.html gh-pages/fief.html
      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
  telegram:
    needs: fief
    runs-on: ubuntu-24.04
    if: ${{ always() }}
    permissions:
      actions: read
    steps:
      - uses: yegor256/terald-action@a0ef862a24f962a4258fd9390d0a67b5529f0eef  # master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat: -1004371404002
